version: 2.1

jobs:
  build-release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install semantic-release
          command: |
            sudo npm install -g semantic-release      \
            @semantic-release/changelog               \
            @semantic-release/commit-analyzer         \
            @semantic-release/exec                    \
            @semantic-release/git                     \
            @semantic-release/release-notes-generator
      - run:
          name: "prepare the release"
          command: "npx semantic-release --prepare"
      - run:
          name: "semantic-release"
          command: "echo ${NEXT_RELEASE_VERSION}"
      - run:
          name: "publish"
          command: "npx semantic-release --publish"

workflows:
  version: 2
  build-release:
    jobs:
      - build-release:
          context: test
