version: 2.1

jobs:
  verify-release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: create empty release version file
          command: |
            echo -n "" > release.version
      - run:
          name: install semantic-release
          command: |
            sudo npm install -g semantic-release      \
            @semantic-release/changelog               \
            @semantic-release/commit-analyzer         \
            @semantic-release/exec                    \
            @semantic-release/git                     \
            @semantic-release/release-notes-generator
      - run:
          name: "Dry run the semantic-release to get next version"
          command: "npx semantic-release --dry-run"
      - persist_to_workspace:
            root: .
            paths:
              - release.version

  release-artifact:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -la
      - run:
          name: Check if next release version is existing. if not halt next steps
          command: |
            if [[ -f "/tmp/workspace/release.version" && -s "/tmp/workspace/release.version" ]];
            then
              echo "There is next release version $(cat /tmp/workspace/release.version)"
            else
              echo "Nothing to release"
              echo "Skip next steps"
              circleci-agent step halt
            fi
      - run:
          name: "test"
          command: "cat /tmp/workspace/release.version"

  publish-release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install semantic-release
          command: |
            sudo npm install -g semantic-release      \
            @semantic-release/changelog               \
            @semantic-release/commit-analyzer         \
            @semantic-release/exec                    \
            @semantic-release/git                     \
            @semantic-release/release-notes-generator
      - run:
          name: "publish"
          command: "npx semantic-release"

workflows:
  version: 2
  build-release:
    jobs:
      - verify-release:
          context: test
      - release-artifact:
          context: test
          requires:
            - verify-release
      - publish-release:
          context: test
          requires:
            - verify-release
            - release-artifact
